services:
  - type: web
    name: meili
    env: docker
    plan: standard
    disk:
      name: meili-data
      mountPath: /data.ms
      sizeGB: 5
    envVars:
      - key: MEILI_HTTP_ADDR
        value: 0.0.0.0:80
      - key: MEILI_MASTER_KEY
        generateValue: true
      - key: MEILI_DB_PATH
        value: /data.ms
      - key: MEILI_ENV
        value: development
