name: Validate

on: [push]

jobs:
  main:
    name: Run type checks, lint, and tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      # - name: Set up tmate session
      #   uses: mxschmitt/action-tmate@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run type checks
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test::ci

      - name: Send Slack notification for job status
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*${{ github.workflow }} #${{ github.run_number }}*'
          url: ${{ secrets.SLATIFY_SLACK_WEBHOOK_URL }}
          token: ${{ secrets.SLATIFY_GITHUB_TOKEN }}
          mention: here
          mention_if: failure
          commit: true
