name: Validate

on: [push]

jobs:
  main:
    name: Run type checks, lint, and tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      # - name: Set up tmate session
      #   uses: mxschmitt/action-tmate@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run type checks
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test::ci

      - name: Send Slack notification for job status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLATIFY_SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
